# Generated by Django 5.2.17 on 2026-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20)),
                ('experience_required', models.CharField(blank=True, max_length=100)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
